//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.AspNetCore.Identity.UI.UIFrameworkAttribute("Bootstrap5")]
[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("aspnet-EJCFitnessGym-3011afb1-0653-4c67-a6c8-d37e6f6b353e")]
[assembly: System.Reflection.AssemblyCompanyAttribute("EJCFitnessGym")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+200881c3d0180c210af1066c2d4525d3044b1f98")]
[assembly: System.Reflection.AssemblyProductAttribute("EJCFitnessGym")]
[assembly: System.Reflection.AssemblyTitleAttribute("EJCFitnessGym")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

